SELECT [EntryId]
      ,s.[Identity]
      ,[MapiIdentity]
      ,s.[Name]
      ,[ParentPath]
      ,[FolderType]
      ,[ReplicaCount]
      ,[Replicas]
      ,[HasRules]
      ,[HasModerator]
      ,[HasItems]
      ,[HasSubFolders]
      ,[FolderCount]
      ,[MailEnabled]
      ,[MailEnabledFolderCount]
      ,[HiddenFromAddressListsEnabled]
      ,[sCreationTime]
      ,[sLastAccessTime]
      ,[sLastModificationTime]
      ,[sLastUserAccessTime]
      ,[sLastUserModificationTime]
      ,[CreationTime]
      ,[DeletedItemCount]
      ,[ItemCount]
      ,[LastAccessTime]
      ,[LastModificationTime]
      ,[LastUserAccessTime]
      ,[LastUserModificationTime]
      ,[OwnerCount]
      ,[TotalDeletedItemSize]
      ,[TotalDeletedItemSizeGB]
      ,[TotalItemSize]
      ,[TotalItemSizeGB]
      ,[AgeLimit]
      ,s.[MaxItemSize]
      ,s.[IssueWarningQuota]
      ,[RetainDeletedItemsFor]
      ,[UseDatabaseAgeDefaults]
      ,[UseDatabaseQuotaDefaults]
      ,[UseDatabaseReplicationSchedule]
      ,[UseDatabaseRetentionDefaults]
	  --,d.RpcClientAccessServer
  FROM [dbo].[PFTreeWithStats] S --JOIN dbo.PFDatabases D ON S.Replicas LIKE '%' + d.[Identity] + '%'
  WHERE HasSubFolders = 0 AND HasItems = 0 AND MailEnabled = 0 
	AND (LastUserAccessTime IS NULL OR LastUserAccessTime < '2019-01-01')
	AND (LastUserModificationTime IS NULL OR LastUserModificationTime < '2019-01-01')
	AND CreationTime < '2019-01-01'

