/****** Script for SelectTopNRows command from SSMS  ******/
SELECT[AssociatedItemCount]
      ,[ContactCount]
      ,[CreationTime]
      ,[DeletedItemCount]
      ,[EntryId]
      ,[FolderPath]
      ,[Identity]
      ,[IsValid]
      ,[ItemCount]
      ,[LastModificationTime]
      ,[MailboxOwnerId]
      ,[Name]
      ,[OwnerCount]
      ,[TotalItemSizeInMB]
      ,[TotalDeletedItemSizeInMB]
      ,[TotalAssociatedItemSizeInMB]
  FROM [Migration].[dbo].[PublicFolderStatistics]
  ORDER by TotalItemSizeInMB Desc