/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [PSComputerName]
      ,[RunspaceId]
      ,[PSShowComputerName]
      ,[Identity]
      ,[Name]
      ,[MailEnabled]
      ,[MailRecipientGuid]
      ,[ParentPath]
      ,[ContentMailboxName]
      ,[ContentMailboxGuid]
      ,[EformsLocaleId]
      ,[PerUserReadStateEnabled]
      ,[EntryId]
      ,[DumpsterEntryId]
      ,[ParentFolder]
      ,[OrganizationId]
      ,[AgeLimit]
      ,[RetainDeletedItemsFor]
      ,[ProhibitPostQuota]
      ,[IssueWarningQuota]
      ,[MaxItemSize]
      ,[LastMovedTime]
      ,[FolderSize]
      ,[HasSubfolders]
      ,[FolderClass]
      ,[FolderPath]
      ,[DefaultFolderType]
      ,[ExtendedFolderFlags]
      ,[MailboxOwnerId]
      ,[IsValid]
      ,[ObjectState]
      ,[ExchangeOrg]
  FROM [Migration].[dbo].[PublicFolder]
  where name like '%/%'