/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [EntryId]
      ,[Identity]
      ,[MapiIdentity]
      ,[Name]
      ,[ParentPath]
      ,[FolderType]
      ,[ReplicaCount]
      ,[Replicas]
      ,[HasRules]
      ,[HasModerator]
      ,[HasItems]
      ,[HasSubFolders]
      ,[FolderCount]
      ,[MailEnabled]
      ,[MailEnabledFolderCount]
      ,[HiddenFromAddressListsEnabled]
      ,[sCreationTime]
      ,[sLastAccessTime]
      ,[sLastModificationTime]
      ,[sLastUserAccessTime]
      ,[sLastUserModificationTime]
      ,[CreationTime]
      ,[DeletedItemCount]
      ,[ItemCount]
      ,[LastAccessTime]
      ,[LastModificationTime]
      ,[LastUserAccessTime]
      ,[LastUserModificationTime]
      ,[OwnerCount]
      ,[TotalDeletedItemSize]
      ,[TotalDeletedItemSizeGB]
      ,[TotalItemSize]
      ,[TotalItemSizeGB]
      ,[AgeLimit]
      ,[MaxItemSize]
      ,[IssueWarningQuota]
      ,[ProhibitPostQuota]
      ,[RetainDeletedItemsFor]
      ,[UseDatabaseAgeDefaults]
      ,[UseDatabaseQuotaDefaults]
      ,[UseDatabaseReplicationSchedule]
      ,[ReplicationSchedule]
      ,[UseDatabaseRetentionDefaults]
  FROM [PFData].[dbo].[PFTreeWithStats]
  wHERe MailEnabled = 1